---
- hosts: all
  roles: 
    - role: oci-rsa-ansible-base
      become: true
    - role: wazuh-odfe
      become: true
    - role: geerlingguy.clamav
      become: true
    - role: wazuh-ansible/wazuh-ansible/roles/opendistro/opendistro-elasticsearch
      become: true