---
- hosts: all
  vars_files:
    - ../extra-variables.yml
  roles: 
    - role: oci-rsa-ansible-base
      become: true
    - role: wazuh-odfe
      become: true
    - role: wazuh-ansible/wazuh-ansible/roles/opendistro/opendistro-elasticsearch
      become: true
    - role: wazuh-ansible/wazuh-ansible/roles/wazuh/ansible-wazuh-agent
      become: true
    - role: oci-rsa-ansible-base/wazuh_agent_configuration
      become: true
 